name: run-tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update platform
      run: sudo apt-get update

    - name: Install GoogleTest libraries
      run: sudo apt-get install libgmock-dev libgtest-dev

    - name: Run tests
      run: ${{github.workspace}}/run-tests.sh
